### PR TITLE
bring back [Test::Portability]

### PR DESCRIPTION
**Pull request by karenetheridge**
it no longer needs to be disabled - see
https://github.com/abraxxa/Test-Portability-Files/pull/5

### CODE REVIEW

**Comment by xdg** [comment]
This doesn't like "_Util".

**Comment by karenetheridge** [comment]
doh! I'll take a look.

**Comment by karenetheridge** [comment]
This should be good to go. I also updated the travis config so it runs xt tests just to make sure.

**Comment by xdg** [comment]
Rebased/squashed and merged

**Pull request closed without merging**
