### PR TITLE
Add support for bumping the version in Build.PL files

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by karenetheridge** [comment]
@autarch we can't convince you to get off of Module::Build? *bambi eyes* :)

**Comment by autarch** [comment]
@karenetheridge - I tried and failed this morning. See https://github.com/autarch/Params-Validate/commit/ef6b64b0b36204b8c8c9f426f7a16de4bcb01998 for a stab at it. Any help you can offer would be appreciated.

That said, there's no reason not apply this PR.

**Comment by autarch** [comment]
I don't think the Travis failures have anything to do with the changes in this branch.

**Comment by autarch** [comment]
Actually, one of the failures was my fault (pod coverage), but the others are not.

**Pull request merged**
